"""soundmatch.core.exporters — headless export utilities.

Three exporters, all in core (no Qt imports) so they are testable headless:

1. **export_snippet**: a runnable Python script that recreates the matched
   phrase via ``render_phrase`` (in the spirit of ``house/strike_intro.py``).

2. **export_markdown**: a characterization report with metric numbers
   (like ``inspiration/black_box/intro_report.md``).

3. **export_montage_png**: a stacked spectrogram PNG (target on top,
   candidate on bottom) using the shared ``draw_spectrogram`` helper.
"""

from __future__ import annotations

import logging
import textwrap
from pathlib import Path
from typing import Any

import numpy as np

log = logging.getLogger(__name__)

from inspector.metrics import Metrics
from soundmatch.core.phrase import Phrase


def export_snippet(
    phrase: Phrase,
    instrument_id: str,
    params: dict[str, Any],
    layers: list[tuple[str, dict[str, Any]]],
    seed: int,
    path: Path,
    *,
    sr: int = 44100,
) -> None:
    """Export a runnable Python script that renders the matched phrase.

    The script can be executed directly (``python snippet.py``) to produce
    a WAV file of the matched sound.

    Parameters
    ----------
    phrase       : The Phrase used for rendering.
    instrument_id: Primary instrument registry key.
    params       : Primary instrument parameters.
    layers       : Additional ``(instrument_id, params)`` pairs.
    seed         : Master seed for deterministic rendering.
    path         : Output ``.py`` path.
    sr           : Sample rate.
    """
    layers_str = (
        "\n".join(f'    ("{iid}", {p!r}),' for iid, p in layers)
        or "    # (no layers)"
    )
    notes_str = "\n".join(
        f"    Note(t={n.t!r}, midi={n.midi!r})," for n in phrase.notes
    )

    snippet = textwrap.dedent(f"""\
        #!/usr/bin/env python3
        \"""Generated by Sound-Match Studio — runnable patch snippet.\"""

        from __future__ import annotations

        import sys
        from pathlib import Path

        from soundmatch.core.candidate import render_phrase
        from soundmatch.core.phrase import Note, Phrase

        def main() -> int:
            phrase = Phrase(
                bpm={phrase.bpm!r},
                length_s={phrase.length_s!r},
                notes=[
        {notes_str}
                ],
                loop={phrase.loop!r},
            )
            buf = render_phrase(
                phrase=phrase,
                instrument_id={instrument_id!r},
                params={params!r},
                layers=[
        {layers_str}
                ],
                seed={seed!r},
                sr={sr!r},
            )
            out = Path(__file__).with_suffix(".wav")
            import soundfile as sf
            y = buf.data.mean(axis=1) if buf.data.ndim == 2 else buf.data
            sf.write(str(out), y, sr)
            print(f"Wrote {{out}}")
            return 0

        if __name__ == "__main__":
            sys.exit(main())
    """)
    path.write_text(snippet, encoding="utf-8")


def export_markdown(
    target_metrics: Metrics,
    cand_metrics: Metrics | None = None,
    scorecard_dict: dict[str, Any] | None = None,
    *,
    reference: str = "",
    instrument_id: str = "",
    path: Path = Path("report.md"),
) -> None:
    """Export a markdown characterization report with metric numbers.

    Parameters
    ----------
    target_metrics : Target Metrics to report.
    cand_metrics   : Optional candidate Metrics.
    scorecard_dict : Optional Scorecard.to_dict() for delta display.
    reference      : Reference audio file name.
    instrument_id  : Instrument used for matching.
    path           : Output ``.md`` path.
    """
    lines: list[str] = []
    lines.append("# Sound-Match Characterization Report\n")
    if reference:
        lines.append(f"**Reference**: `{reference}`\n")
    if instrument_id:
        lines.append(f"**Instrument**: `{instrument_id}`\n")
    lines.append("")

    # Target metrics table
    lines.append("## Target Metrics\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    m = target_metrics
    lines.append(f"| Percussive Ratio | {m.percussive_ratio:.1f}% |")
    lines.append(f"| Spectral Centroid | {m.centroid_hz:.0f} Hz |")
    lines.append(f"| Onset Count | {m.onset_count} |")
    lines.append(f"| Onset Density | {m.onset_density:.1f} events/s |")
    lines.append(f"| Median IOI | {m.median_ioi_s:.3f} s |")

    # Band balance
    lines.append("")
    lines.append("### Band Balance\n")
    lines.append("| Band | % |")
    lines.append("|------|---|")
    for band, pct in sorted(m.band_balance.items()):
        lines.append(f"| {band} | {pct:.1f}% |")

    # Band decay
    lines.append("")
    lines.append("### Band Decay\n")
    lines.append("| Band | ms |")
    lines.append("|------|----|")
    for band, ms in sorted(m.band_decay_ms.items()):
        lines.append(f"| {band} | {ms:.1f} ms |")

    # Chord
    lines.append("")
    lines.append("### Chord Detection\n")
    chord = m.chord
    if chord:
        pcs = ", ".join(chord.get("pitch_classes", []))
        midis = ", ".join(str(n) for n in chord.get("midi", []))
        sub = "yes" if chord.get("sub_octave") else "no"
        lines.append(f"- Pitch classes: {pcs}")
        lines.append(f"- MIDI notes: {midis}")
        lines.append(f"- Sub-octave: {sub}")

    # Candidate comparison (if provided)
    if cand_metrics is not None and scorecard_dict is not None:
        lines.append("")
        lines.append("## Candidate Comparison\n")
        lines.append("| Metric | Target | Candidate | Δ |")
        lines.append("|--------|--------|-----------|---|")

        for key in ("percussive_ratio", "centroid_hz", "onset_count",
                     "onset_density", "median_ioi_s"):
            entry = scorecard_dict.get(key, {})
            t_val = entry.get("target", "—")
            c_val = entry.get("candidate", "—")
            delta = entry.get("delta", "—")
            if isinstance(t_val, float):
                t_val = f"{t_val:.2f}"
            if isinstance(c_val, float):
                c_val = f"{c_val:.2f}"
            if isinstance(delta, float):
                delta = f"{delta:.2f}"
            lines.append(f"| {key} | {t_val} | {c_val} | {delta} |")

        # Band balance deltas
        bb = scorecard_dict.get("band_balance", {})
        if bb:
            lines.append("")
            lines.append("### Band Balance Δ\n")
            lines.append("| Band | Target | Candidate | Δ |")
            lines.append("|------|--------|-----------|---|")
            for band, entry in sorted(bb.items()):
                t_val = f"{entry['target']:.1f}" if isinstance(entry.get("target"), float) else "—"
                c_val = f"{entry['candidate']:.1f}" if isinstance(entry.get("candidate"), float) else "—"
                delta = f"{entry['delta']:.1f}" if isinstance(entry.get("delta"), float) else "—"
                lines.append(f"| {band} | {t_val} | {c_val} | {delta} |")

        # Aggregate
        agg = scorecard_dict.get("aggregate")
        if agg is not None:
            lines.append("")
            lines.append(f"**Aggregate distance**: {agg:.4f}\n")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def export_montage_png(
    target_y: np.ndarray,
    target_sr: int,
    cand_y: np.ndarray,
    cand_sr: int,
    path: Path,
) -> None:
    """Export a stacked spectrogram montage PNG (target on top, candidate below).

    Uses the shared ``draw_spectrogram`` helper — no copy-paste.

    Parameters
    ----------
    target_y  : Target mono audio.
    target_sr : Target sample rate.
    cand_y    : Candidate mono audio.
    cand_sr   : Candidate sample rate.
    path      : Output ``.png`` path.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from soundmatch.ui.spectrogram import draw_spectrogram

    fig, axes = plt.subplots(2, 1, figsize=(8, 4), tight_layout=True)
    draw_spectrogram(axes[0], target_y, target_sr, title="A — Target")
    draw_spectrogram(axes[1], cand_y, cand_sr, title="B — Candidate")
    fig.savefig(str(path), dpi=150)
    plt.close(fig)
